//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalizSonucu
    {
        public int AnalizID { get; set; }
        public Nullable<int> OturumID { get; set; }
        public string AnalizTipi { get; set; }
        public string Metodoloji { get; set; }
        public string MetricsJSON { get; set; }
        public string Summary { get; set; }
        public System.DateTime AnalizTarihi { get; set; }
    
        public virtual Oturum Oturum { get; set; }
    }
}
