//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeneyGrubu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeneyGrubu()
        {
            this.Kullanici = new HashSet<Kullanici>();
        }
    
        public int DeneyGrubuID { get; set; }
        public string GrupAdi { get; set; }
        public string Aciklama { get; set; }
        public bool Aktif { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici { get; set; }
    }
}
