//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EEGVerisi
    {
        public int EEGID { get; set; }
        public int OturumID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<double> Delta { get; set; }
        public Nullable<double> Theta { get; set; }
        public Nullable<double> LowAlpha { get; set; }
        public Nullable<double> HighAlpha { get; set; }
        public Nullable<double> LowBeta { get; set; }
        public Nullable<double> HighBeta { get; set; }
        public Nullable<double> LowGamma { get; set; }
        public Nullable<double> HighGamma { get; set; }
        public Nullable<int> BlinkStrength { get; set; }
        public System.DateTime KayitZamani { get; set; }
        public Nullable<int> SinyalKalitesi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Oturum Oturum { get; set; }
    }
}
