//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.EEGVerisi = new HashSet<EEGVerisi>();
            this.Oturum = new HashSet<Oturum>();
            this.KullaniciModulYetkisi = new HashSet<KullaniciModulYetkisi>();
        }
    
        public int KullaniciID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string SifreHash { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Rol { get; set; }
        public string Notlar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEGVerisi> EEGVerisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oturum> Oturum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciModulYetkisi> KullaniciModulYetkisi { get; set; }
    }
}
