//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciModulYetkisi
    {
        public int YetkiID { get; set; }
        public int KullaniciID { get; set; }
        public string ModulAdi { get; set; }
        public bool AktifMi { get; set; }
        public System.DateTime TanimTarihi { get; set; }
        public Nullable<int> TanimlayanYoneticiID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
