//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eegDBEntities : DbContext
    {
        public eegDBEntities()
            : base("name=eegDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalizSonucu> AnalizSonucu { get; set; }
        public virtual DbSet<EEGVerisi> EEGVerisi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Oturum> Oturum { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<SinavSonucu> SinavSonucu { get; set; }
        public virtual DbSet<KullaniciModulYetkisi> KullaniciModulYetkisi { get; set; }
        public virtual DbSet<DeneyTuru> DeneyTuru { get; set; }
        public virtual DbSet<ZamanEtiketi> ZamanEtiketi { get; set; }
        public virtual DbSet<SinavAtama> SinavAtama { get; set; }
        public virtual DbSet<SinavCevap> SinavCevap { get; set; }
    }
}
