//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oturum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oturum()
        {
            this.AnalizSonucu = new HashSet<AnalizSonucu>();
            this.EEGVerisi = new HashSet<EEGVerisi>();
            this.SinavSonucu = new HashSet<SinavSonucu>();
        }
    
        public int OturumID { get; set; }
        public int KullaniciID { get; set; }
        public string ZamanEtiketi { get; set; }
        public string DeneyTuru { get; set; }
        public Nullable<System.DateTime> KayitBaslangic { get; set; }
        public Nullable<System.DateTime> KayitBitis { get; set; }
        public string Notlar { get; set; }
        public Nullable<int> DeneyTuruID { get; set; }
        public Nullable<int> ZamanEtiketiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalizSonucu> AnalizSonucu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EEGVerisi> EEGVerisi { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavSonucu> SinavSonucu { get; set; }
        public virtual DeneyTuru DeneyTuru1 { get; set; }
        public virtual ZamanEtiketi ZamanEtiketi1 { get; set; }
    }
}
