//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavCevap
    {
        public int CevapID { get; set; }
        public int SinavSonucuID { get; set; }
        public int SoruNo { get; set; }
        public string SoruTipi { get; set; }
        public string SoruMetni { get; set; }
        public string DogruCevap { get; set; }
        public string VerilenCevap { get; set; }
        public Nullable<int> CevaplamaSuresi { get; set; }
        public bool DogruMu { get; set; }
        public Nullable<double> ToplamPuan { get; set; }
        public Nullable<double> AlinanPuan { get; set; }
        public string AnahtarKelimelerJson { get; set; }
        public string EslesenAnahtarKelimeler { get; set; }
        public Nullable<double> EslesmeYuzdesi { get; set; }
        public System.DateTime CevapTarihi { get; set; }
    
        public virtual SinavSonucu SinavSonucu { get; set; }
    }
}
