//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavSonucu
    {
        public int SinavSonucuID { get; set; }
        public int OturumID { get; set; }
        public string SinavTuru { get; set; }
        public int ToplamSoru { get; set; }
        public int DogruSayisi { get; set; }
        public int YanlisSayisi { get; set; }
        public System.DateTime BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string Sure { get; set; }
    
        public virtual Oturum Oturum { get; set; }
    }
}
