//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavAtama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinavAtama()
        {
            this.SinavSonucu = new HashSet<SinavSonucu>();
        }
    
        public int AtamaID { get; set; }
        public int KullaniciID { get; set; }
        public string SinavAdi { get; set; }
        public string SinavAciklama { get; set; }
        public string SinavJsonPath { get; set; }
        public string SinavJsonContent { get; set; }
        public int AtayanYoneticiID { get; set; }
        public System.DateTime AtamaTarihi { get; set; }
        public Nullable<System.DateTime> SonGecerlilikTarihi { get; set; }
        public bool TamamlandiMi { get; set; }
        public Nullable<System.DateTime> TamamlanmaTarihi { get; set; }
        public string Notlar { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavSonucu> SinavSonucu { get; set; }
    }
}
