//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eegProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        public int YoneticiID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Email { get; set; }
        public string SifreHash { get; set; }
        public string YetkiSeviyesi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public bool AnalizModuluAktifMi { get; set; }
    }
}
