            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1184, 761);
            this.Controls.Add(this.tabMain);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject(".Icon")));
            this.Name = "Form1";
            this.Text = "EEG Yonetim Paneli";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.gridLogs)).EndInit();
            this.tabPageLogs.ResumeLayout(false);
            this.tabPageLogs.PerformLayout();
            this.panelExport.ResumeLayout(false);
            this.panelExport.PerformLayout();
            this.tabPageExport.ResumeLayout(false);
            this.tabPageExport.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridAnalyses)).EndInit();
            this.panelAnalysisActions.ResumeLayout(false);
            this.panelAnalysisActions.PerformLayout();
            this.tabPageAnalysis.ResumeLayout(false);
            this.tabPageAnalysis.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridEEG)).EndInit();
            this.panelEEGActions.ResumeLayout(false);
            this.panelEEGActions.PerformLayout();
            this.tabPageEEG.ResumeLayout(false);
            this.tabPageEEG.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridSessions)).EndInit();
            this.panelSessionsActions.ResumeLayout(false);
            this.panelSessionsActions.PerformLayout();
            this.tabPageSessions.ResumeLayout(false);
            this.tabPageSessions.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).EndInit();
            this.panelUsersActions.ResumeLayout(false);
            this.panelUsersActions.PerformLayout();
            this.tabPageUsers.ResumeLayout(false);
            this.tabPageUsers.PerformLayout();
            this.tabMain.ResumeLayout(false);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabPageUsers;
        private System.Windows.Forms.DataGridView gridUsers;
        private System.Windows.Forms.FlowLayoutPanel panelUsersActions;
        private System.Windows.Forms.Button btnRefreshUsers;
        private System.Windows.Forms.Button btnAddUser;
        private System.Windows.Forms.Button btnEditUser;
        private System.Windows.Forms.Button btnDeleteUser;
        private System.Windows.Forms.Button btnResetPassword;
        private System.Windows.Forms.TabPage tabPageSessions;
        private System.Windows.Forms.DataGridView gridSessions;
        private System.Windows.Forms.FlowLayoutPanel panelSessionsActions;
        private System.Windows.Forms.Button btnRefreshSessions;
        private System.Windows.Forms.Button btnAddSession;
        private System.Windows.Forms.Button btnEditSession;
        private System.Windows.Forms.Button btnDeleteSession;
        private System.Windows.Forms.Button btnManageExperimentTypes;
        private System.Windows.Forms.Button btnManageTimeLabels;
        private System.Windows.Forms.TabPage tabPageEEG;
        private System.Windows.Forms.DataGridView gridEEG;
        private System.Windows.Forms.FlowLayoutPanel panelEEGActions;
        private System.Windows.Forms.Button btnRefreshEEG;
        private System.Windows.Forms.ComboBox cmbEegSessions;
        private System.Windows.Forms.Button btnStreamMonitor;
        private System.Windows.Forms.Button btnStopStream;
        private System.Windows.Forms.Label lblStreamStatus;
        private System.Windows.Forms.TabPage tabPageAnalysis;
        private System.Windows.Forms.DataGridView gridAnalyses;
        private System.Windows.Forms.FlowLayoutPanel panelAnalysisActions;
        private System.Windows.Forms.Button btnRefreshAnalysis;
        private System.Windows.Forms.Button btnTriggerAnalysis;
        private System.Windows.Forms.Button btnViewMetrics;
        private System.Windows.Forms.TabPage tabPageExport;
        private System.Windows.Forms.FlowLayoutPanel panelExport;
        private System.Windows.Forms.Button btnExportExcel;
        private System.Windows.Forms.Button btnExportJson;
        private System.Windows.Forms.TabPage tabPageLogs;
        private System.Windows.Forms.DataGridView gridLogs;
        private System.Windows.Forms.Button btnRefreshLogs;
    }
}
